apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector-dep
spec:
  selector:
    matchLabels:
      app: collector-dep
  template:
    metadata:
      labels:
        app: collector-dep
    spec:
      serviceAccountName: collector-sa  # Specify the ServiceAccount
      containers:
      - name: collector-dep
        image: otel/opentelemetry-collector-contrib:0.104.0
        args: ["--config=/etc/otelcol-contrib/otel-collector.yml"]
        volumeMounts:
         - name: otel-collector-config-vol
           mountPath: /etc/otelcol-contrib/otel-collector.yml
           subPath: otel-collector.yml
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-config
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: collector-dep
spec:
  selector:
    app: collector-dep
  ports:
    - name: otlp-grpc # Default endpoint for OpenTelemetry gRPC receiver.
      port: 4317
      protocol: TCP
      targetPort: 4317
    - name: otlp-http # Default endpoint for OpenTelemetry HTTP receiver.
      port: 4318
      protocol: TCP
      targetPort: 4318
    - name: metrics # Default endpoint for querying metrics.
      port: 8888
  type: NodePort
